## For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html
#
# Specifies the JVM arguments used for the daemon process.
# The setting is particularly useful for tweaking memory settings.
# Default value: -Xmx1024m -XX:MaxPermSize=256m
# org.gradle.jvmargs=-Xmx2048m -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
#
# When configured, Gradle will run in incubating parallel mode.
# This option should only be used with decoupled projects. For more details, visit
# https://developer.android.com/r/tools/gradle-multi-project-decoupled-projects
# org.gradle.parallel=true
#Mon Jul 08 14:26:52 WIB 2024
# === Gradle Performance ===
org.gradle.daemon=true
org.gradle.daemon.performance.enable-monitoring=false
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.problems=warn
org.gradle.configuration-cache.parallel=true
org.gradle.configureondemand=true
org.gradle.jvmargs=-XX:+UnlockExperimentalVMOptions -Xmx3g -Xms3g -XX:MetaspaceSize=812m -Dfile.encoding=UTF-8 -XX:SoftRefLRUPolicyMSPerMB=1 -XX:+UseG1GC -XX:+HeapDumpOnOutOfMemoryError
#=== Kotlin / Native ===
kotlin.code.style=official
kotlin.compiler.execution.strategy=in-process
kotlin.incremental.native=true
kotlin.daemon.jvmargs=-XX:+UnlockExperimentalVMOptions -Xmx3g -Xms3g -XX:MetaspaceSize=812m -Dfile.encoding=UTF-8 -XX:SoftRefLRUPolicyMSPerMB=1 -XX:+UseG1GC -XX:+HeapDumpOnOutOfMemoryError
#=== android / Native ===
android.useAndroidX=true
android.nonTransitiveRClass=true